// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TesteOCTO_Tecnologia.Data;

namespace TesteOCTO_Tecnologia.Migrations
{
    [DbContext(typeof(TesteOCTO_TecnologiaContext))]
    partial class TesteOCTO_TecnologiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CrudOCTOTecnologia.Models.PessoaFisica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DTNascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PessoaFisica");
                });

            modelBuilder.Entity("CrudOCTOTecnologia.Models.PessoaJuridica", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CNPJ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RazaoSocial")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PessoaJuridica");
                });

            modelBuilder.Entity("TesteOCTO_Tecnologia.Models.Endereco", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Bairro")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CEP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cidade")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Complemento")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaFisicaID")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaJuridicaID")
                        .HasColumnType("int");

                    b.Property<byte>("tipoEndereco")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("PessoaFisicaID");

                    b.HasIndex("PessoaJuridicaID");

                    b.ToTable("Endereco");
                });

            modelBuilder.Entity("TesteOCTO_Tecnologia.Models.Telefone", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DDD")
                        .HasColumnType("int");

                    b.Property<int>("Numero")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaFisicaID")
                        .HasColumnType("int");

                    b.Property<int?>("PessoaJuridicaID")
                        .HasColumnType("int");

                    b.Property<byte>("tipoTelefone")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.HasIndex("PessoaFisicaID");

                    b.HasIndex("PessoaJuridicaID");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("TesteOCTO_Tecnologia.Models.Endereco", b =>
                {
                    b.HasOne("CrudOCTOTecnologia.Models.PessoaFisica", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaFisicaID");

                    b.HasOne("CrudOCTOTecnologia.Models.PessoaJuridica", null)
                        .WithMany("Enderecos")
                        .HasForeignKey("PessoaJuridicaID");
                });

            modelBuilder.Entity("TesteOCTO_Tecnologia.Models.Telefone", b =>
                {
                    b.HasOne("CrudOCTOTecnologia.Models.PessoaFisica", null)
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaFisicaID");

                    b.HasOne("CrudOCTOTecnologia.Models.PessoaJuridica", null)
                        .WithMany("Telefones")
                        .HasForeignKey("PessoaJuridicaID");
                });
#pragma warning restore 612, 618
        }
    }
}
